Collections:
- Name: gwd
  Metadata:
    Training Data: DOTAv1.0
    Training Techniques:
      - SGD with Momentum
      - Weight Decay
    Training Resources: 1x GeForce GTX 1080 Ti
    Architecture:
      - ResNet
  Paper:
    URL: https://arxiv.org/pdf/2101.11952.pdf
    Title: 'Rethinking Rotated Object Detection with Gaussian Wasserstein Distance Loss'
  README: configs/gwd/README.md

Models:
  - Name: rotated_retinanet_hbb_gwd_r50_fpn_1x_dota_oc
    In Collection: gwd
    Config: configs/gwd/rotated_retinanet_hbb_gwd_r50_fpn_1x_dota_oc.py
    Metadata:
      Training Data: DOTAv1.0
    Results:
      - Task: Oriented Object Detection
        Dataset: DOTAv1.0
        Metrics:
          mAP: 69.55
    Weights: https://download.openmmlab.com/mmrotate/v0.1.0/gwd/rotated_retinanet_hbb_gwd_r50_fpn_1x_dota_oc/rotated_retinanet_hbb_gwd_r50_fpn_1x_dota_oc-41fd7805.pth
