Collections:
- Name: roi_trans
  Metadata:
    Training Data: DOTAv1.0
    Training Techniques:
      - SGD with Momentum
      - Weight Decay
      - AdamW
    Training Resources: 1x GeForce GTX 1080 Ti
    Architecture:
      - ResNet
      - Swin
  Paper:
    URL: https://openaccess.thecvf.com/content_CVPR_2019/papers/Ding_Learning_RoI_Transformer_for_Oriented_Object_Detection_in_Aerial_Images_CVPR_2019_paper.pdf
    Title: 'Learning RoI Transformer for Oriented Object Detection in Aerial Images'
  README: configs/roi_trans/README.md

Models:
  - Name: roi_trans_r50_fpn_1x_dota_le90
    In Collection: roi_trans
    Config: configs/roi_trans/roi_trans_r50_fpn_1x_dota_le90.py
    Metadata:
      Training Data: DOTAv1.0
    Results:
      - Task: Oriented Object Detection
        Dataset: DOTAv1.0
        Metrics:
          mAP: 76.08
    Weights: https://download.openmmlab.com/mmrotate/v0.1.0/roi_trans/roi_trans_r50_fpn_1x_dota_le90/roi_trans_r50_fpn_1x_dota_le90-d1f0b77a.pth

  - Name: roi_trans_swin_tiny_fpn_1x_dota_le90
    In Collection: roi_trans
    Config: configs/roi_trans/roi_trans_swin_tiny_fpn_1x_dota_le90.py
    Metadata:
      Training Data: DOTAv1.0
    Results:
      - Task: Oriented Object Detection
        Dataset: DOTAv1.0
        Metrics:
          mAP: 77.51
    Weights: https://download.openmmlab.com/mmrotate/v0.1.0/roi_trans/roi_trans_swin_tiny_fpn_1x_dota_le90/roi_trans_swin_tiny_fpn_1x_dota_le90-ddeee9ae.pth

  - Name: roi_trans_r50_fpn_1x_dota_ms_le90
    In Collection: roi_trans
    Config: configs/roi_trans/roi_trans_r50_fpn_1x_dota_ms_le90.py
    Metadata:
      Training Data: DOTAv1.0
    Results:
      - Task: Oriented Object Detection
        Dataset: DOTAv1.0
        Metrics:
          mAP: 79.66
    Weights: https://download.openmmlab.com/mmrotate/v0.1.0/roi_trans/roi_trans_r50_fpn_1x_dota_ms_rr_le90/roi_trans_r50_fpn_1x_dota_ms_rr_le90-fa99496f.pth
